Feature/112 calendar
DeveloperAcademy-POSTECH/MacC-Team-Trying-iOS pull request #124
Opened 2022-11-08 09:25 UTC by wody-d

## 🔍 개요
- #112 

## 📝 작업사항
- 캘린더 구현 (아래의 기능을 가짐)

1. 스케줄이 점으로 찍힙니다.
2. 5주일 때, 6주일 때, 높이가 자동으로 조절됩니다.
3. 주간 월간으로 변경 버튼이 있습니다.
4. 월이 변경될 때 선택된 날짜는 1일로 변경됩니다.

### 사용법 

아래 코드의 `MARK` 표시 읽기

```swift

import UIKit
import SnapKit

class TestViewController: UIViewController {

    override func viewDidLoad() {
        super.viewDidLoad()

        lazy var calendarView = CalendarView(today: .init(), frame: .init(origin: .zero, size: .init(width: DeviceInfo.screenWidth - 40, height: 0)))

        // MARK: 캘린더 스케쥴 점찍기
        calendarView.scheduleList = [
            YearMonthDayDate(year: 2022, month: 10, day: 31),
            YearMonthDayDate(year: 2022, month: 11, day: 6),
            YearMonthDayDate(year: 2022, month: 11, day: 10),
            YearMonthDayDate(year: 2022, month: 11, day: 23),
            YearMonthDayDate(year: 2022, month: 11, day: 30)
        ]

        view.addSubview(calendarView)
        calendarView.delegate = self
        // MARK: 높이는 캘린더뷰가 조절합니다. 고정하지 않기
        calendarView.snp.makeConstraints { make in
            make.top.equalToSuperview().offset(140)
            make.leading.trailing.equalToSuperview().inset(20)
        }

        let blueView = UIView()
        view.addSubview(blueView)
        blueView.backgroundColor = .blue
        blueView.snp.makeConstraints { make in
            make.top.equalTo(calendarView.snp.bottom).offset(100)
            make.width.height.equalTo(40)
            make.centerX.equalToSuperview()
        }
    }
}

extension TestViewController: CalendarViewDelegate {
    func scrollViewDidEndDecelerating() {
        UIView.animate(withDuration: 0.3, delay: 0) {
            self.view.layoutIfNeeded()
        }
    }

    func switchCalendarButtonDidTapped() {
        UIView.animate(withDuration: 0.3, delay: 0) {
            self.view.layoutIfNeeded()
        }
    }

    // MARK: 캘린더 선택된 날짜 가져오기
    func selectDate(_ date: Date?) {
        print(date)
        print(date?.toString())
    }
}
```
## 📸 스크린샷 또는 영상

<p>
  <img src="https://user-images.githubusercontent.com/56102421/200526466-a204b878-fb98-4c63-b9d8-458f0fc7af29.gif" width="300">
</p>

## 📄 Reference
 
제 블로그 달력 글

2022-11-09 03:37 UTC, kimscastle approved these changes
사용방법 보고 잘 사용해보겟습니다^^

2022-11-09 03:48 UTC, kyustudyo approved these changes
멋집니다

2022-11-09 03:48 UTC, kyustudyo commented on Sources/App/AppDelegate.swift
> +        window?.rootViewController = TestViewController()
TestViewController 발견~!

2022-11-09 03:48 UTC, kyustudyo commented on Sources/DesignSystem/Views/Calendar/CalendarView.swift
> +            numberOfDaysInMonth[1] = 29
윤년 평년 적용이 되어있넹 ㅎㅎ 굿이네요

2022-11-09 04:00 UTC, luminouxx requested changes

2022-11-09 04:00 UTC, luminouxx commented on Sources/App/AppDelegate.swift
> +        window?.rootViewController = TestViewController()
이것만 지우고 머지합시다.

2022-11-10 00:40 UTC, wody-d commented on Sources/App/AppDelegate.swift
> +        window?.rootViewController = TestViewController()
이런~

2022-11-10 15:44 UTC, merged