✨Coordinator 생성
DeveloperAcademy-POSTECH/MacC-Team-Trying-iOS pull request #13
Opened 2022-10-12 12:45 UTC by LentoAssai

## 🔍 개요
#5 Coordinator 프레임 잡기

## 📝 작업사항
- AppDelegate에서 AppCoordinator를 통해 화면을 보여줍니다.
(Coordinator로 구현이 안되어 있을 때는 AppDelegate에서 임시로 화면을 띄워서 테스트 해주세요)
(커밋 찍을때는 AppDelegate 빼고 커밋해주세요)
- Coordinator Protocol 생성
- AppCoordinator, LoginCoordinator, MainCoordinator 생성
- MainCoordinator 하위에 Home, Search, Feed, Profile Coordinator 생성
- 테스트용 Home, Search, Feed, Profile ViewController 및 ViewModel 생성

## 📸 스크린샷 또는 영상

### 테스트 화면
<p>
  <img src="https://user-images.githubusercontent.com/88371913/195344711-201c5c40-3674-49cd-b6be-11ae0add8160.png" width="300">
</p>

### Coordinator 구조
<img width="700" alt="스크린샷 2022-10-12 21 41 53" src="https://user-images.githubusercontent.com/88371913/195345151-406667ba-7449-4e80-8a9c-5b0ef273f63f.png">

## 🧐 참고 사항
- 일반적으로 사용하는 parent, child coordinator 관계를 사용하지 않고 coordinator가 view에 의존하는 형태로 구현을 해서 메모리 상으로 어떤 side effect가 있을지 모르겠습니다. 후에 문제가 있으면 다시 parent, child 형식으로 수정할 계획입니다.

2022-10-12 17:10 UTC, wody-d requested changes
👍🏻

참고한 레퍼런스 자료 pr에 첨부 부탁~

코디네이터에서 `UINavigationController`를 `presenter` 네이밍을 사용했는데 어떤 생각으로 사용했는지 궁금해 현재 큰 폴더명도 Domain, Presenter, Coordinator로 나뉘고 있는데 여기서 사용되는 Presenter와 다른 기능이지만 같은 이름이라 구분되었으면 좋겠어. 그냥 말그대로 `navigationController`라고 하거나 공통되게 사용될 UI 컴포넌트니까 `commonNavigation`도 좋을 것 같은 생각 

또, Coordinator가 하나의 폴더로 묶여있는데, 난 화면전환 또한 Login, Home, Profile, Feed, Search 각각의 도메인에 포함되는 요소라고 생각해서 따로 폴더링을 하는 건 이후에 모듈을 분리할 일이 생기면 불편할 거 같아. 또 개발하면서 해당 폴더로 계속 접근해야할일이 생겨서 navigator에서 찾는데도 시간이 많이 소요될거라고 생각해. 오히려 해당 도메인 각각에 존재하면 좋지않을까? 

그리고 Coordinator 인스턴스는 VM에서 가지고 있을 예정이야? 아니면 VC에서 가지고 있을 예정이야? (궁금)

마지막으로 참고사항에 적어놓은 parent와 child 코디네이터의 관계가 무슨 말인지 이해가 되지 않는데 설명해줄 수 있을까? 코디네이터가 뷰에 의존하는 형태로 구현을 했다는 게 이해가 안간다.

ps) 화면사이 데이터 전달은 회원가입할 때 데이터가 많이 넘겨지기 때문에 필요한 거여서 이슈에 만들어달라고 부탁한 거였는데 내가 개발할 때 데이터가 너무 많아지면 그때가서 생각해볼게

2022-10-13 02:51 UTC, LentoAssai commented on Templates/MVVM.xctemplate/___FILEBASENAME___/___FILEBASENAME___ViewController.swift
> +    private func setLayout() {
봐주세여..
템플릿은 지금 나만 건드리고 있고 1줄 바꾸려고 이슈 등록->브랜치생성->PR 후 머지는 귀찮아서..ㅠㅠ
이런 상황이어도 절차대로 하는게 좋을까?

2022-10-13 02:51 UTC, LentoAssai commented on Sources/Coordinator/Main/MainCoordinator.swift
> +    var tabBarItems: [TabBarItem] = [ .home, .search, .feed, .profile]
Good

2022-10-13 02:52 UTC, wody-d commented on Templates/MVVM.xctemplate/___FILEBASENAME___/___FILEBASENAME___ViewController.swift
> +    private func setLayout() {
유도리 있게 ㄲ~ 근데 PR내용에는 적어주자

2022-10-13 02:54 UTC, LentoAssai commented on Sources/Coordinator/Main/MainCoordinator.swift
> +    var tabBarItems: [TabBarItem] = [ .home, .search, .feed, .profile]
4ddfd318158a1e071a8b1ffb3bd8cdbfe2714904
let으로 변경 커밋

2022-10-13 02:56 UTC, LentoAssai commented on Templates/MVVM.xctemplate/___FILEBASENAME___/___FILEBASENAME___ViewController.swift
> +    private func setLayout() {
반영이요~

2022-10-13 02:58 UTC, LentoAssai commented on Sources/Coordinator/Main/MainCoordinator.swift
> +    var tabBarItems: [TabBarItem] = [ .home, .search, .feed, .profile]
presenter 변수는 layer의 presenter와 구분되긴 하지만 이름이 같으니까 헷갈릴 수도 있겠네
`navigationController`로 바꿀게

2022-10-13 03:08 UTC, LentoAssai commented on Sources/Coordinator/Main/MainCoordinator.swift
> +    var tabBarItems: [TabBarItem] = [ .home, .search, .feed, .profile]
>또, Coordinator가 하나의 폴더로 묶여있는데, 난 화면전환 또한 Login, Home, Profile, Feed, Search 각각의 도메인에 포함되는 요소라고 생각해서 따로 폴더링을 하는 건 이후에 모듈을 분리할 일이 생기면 불편할 거 같아. 또 개발하면서 해당 폴더로 계속 접근해야할일이 생겨서 네비게이터에서 찾는데도 시간이 많이 소요될거라고 생각해. 오히려 해당 도메인 각각에 존재하면 좋지않을까?

그럼 Presenter 디렉토리 안에 Login, Home, Search, Feed, Profile 이런 식으로 디렉토리가 만들어질 것 같은데 그 안에 각각의 Coordinator를 넣자는 말이지?
후에 모듈 분리를 생각하는거랑 이런거는 아직 경험이 부족해서 나중을 위해 어떻게 해놓으면 편할지는 아직 잘 모르겠어
example project 찾아볼 때에도 큰 Coordinator 말고 각각의 Coordinator는 안쪽(?)에 있던데
(AppCoordinator는 밖에, Home, Search, Feed 이런 것들은 각각의 디렉토리 안에)
그렇게 했을 때의 장점이 뭔지 잘 모르겠고
그리고 Coordinator관련해서는 내가 담당할 예정이어서 (Login쪽은 너가 할수도 있겠지만) 따로 빼서 하는게 편할거 같아서 뺐었어

2022-10-13 03:14 UTC, LentoAssai commented on Sources/Coordinator/Main/MainCoordinator.swift
> +    var tabBarItems: [TabBarItem] = [ .home, .search, .feed, .profile]
>그리고 Coordinator 인스턴스는 VM에서 가지고 있을 예정이야? 아니면 VC에서 가지고 있을 예정이야? (궁금)
마지막으로 참고사항에 적어놓은 parent와 child 코디네이터의 관계가 무슨 말인지 이해가 되지 않는데 설명해줄 수 있을까? 코디네이터가 뷰에 의존하는 형태로 구현을 했다는 게 이해가 안간다.

VM이 가지게 할거구 parent, child는 Coordinator 검색해보면 하위 Flow를 담당하는 child coordinator가 deallocated 되지 않기 위해서 parent에서는 `childCoordinators`라는 프로퍼티에 append시키고, child에서는
```swift
weak var parent: Coordinator?
```
이런식으로 참조시켜서 allocating을 방지하는데 (flow가 끝났을 때 delegate으로도 사용 가능하고)
근데 이렇게 하면 boilerplate code가 많아져서 [블로그](https://medium.com/vptech/coordinator-pattern-in-swift-without-child-coordinators-42d482d15975)에 소개된 방법으로 해봤어
위 방법으로 하면 coordinator가 view가 없어지면 자동으로 deallocated되어서 굳이 flow가 끝났을 때 코드를 작성할 필요가 없어져서 코드 작성을 까먹는 실수나 boilerplate code들을 줄일 수 있는 장점이 있어서.

<img width="700" alt="스크린샷 2022-10-13 12 13 50" src="https://user-images.githubusercontent.com/88371913/195490754-e4b46819-e351-4c97-89db-1407f28d10b5.png">

이런식으로 될거고 VM에서 coordinator를 가지게 될거야

2022-10-13 03:17 UTC, LentoAssai commented on Sources/Coordinator/Main/MainCoordinator.swift
> +    var tabBarItems: [TabBarItem] = [ .home, .search, .feed, .profile]
>ps) 화면사이 데이터 전달은 회원가입할 때 데이터가 많이 넘겨지기 때문에 필요한 거여서 이슈에 만들어달라고 부탁한 거였는데 내가 개발할 때 데이터가 너무 많아지면 그때가서 생각해볼게

코디네이터 패턴에서 데이터 전달을 찾아보긴 했는데 다 코디네이터를 통해서 데이터 전달을 하더라고
전달할 데이터가 많아지면 불편해지기도 하고 SwiftLint rule도 인자 많이는 받지 않게 적용을 해서 나중에 뭔가 warning이나 문제가 있을거 같긴한데..
데이터 전달 더 찾아보다가 좋은거 발견하면 적용해볼게
일단 나중에 생각해보자

2022-10-13 03:59 UTC, wody-d commented
이거 왜 코드 댓글에 다는거지?? 여기다가 달아
> 그리고 Coordinator관련해서는 내가 담당할 예정이어서 (Login쪽은 너가 할수도 있겠지만) 따로 빼서 하는게 편할거 같아서 뺐었어

지금 이 말이 살짝 이해가 안가. Coordinator는 화면전환인데 다른 사람들도 화면전환 코드를 다뤄야하기 때문에 각각의 피쳐에 포함시키는거야. 한사람이 관리하면 충돌은 안나겠지만(~~이 충돌도 눈으로 보이기때문에 해결하기 쉬움~~), 동기적으로 작업이 되기 때문에 시간이 더 오래 걸려. 따라서, 각자가 작업하기 위해서 각 피쳐 폴더 안에 넣는거야 그리고 위에 단점 몇가지를 더 적어놨어. 너가 생각하는 화면전환을 따로 폴더를 만들어서 관리하는 장점이 뭘까?

>  coordinator가 view가 없어지면 자동으로 deallocated되어서 굳이 flow가 끝났을 때 코드를 작성할 필요가 없어져서 코드 작성을 까먹는 실수나 boilerplate code들을 줄일 수 있는 장점이 있어서.

저블로그가 소개하는 방식이 이해가 가지 않는데 코디네이터는 VC를 들고 있을텐데 왜 view가 없어지면 자동으로 할당해제되는거지? 아래 코디네이터에는 네비게이션 인스턴스를 약한 참조하고 있고, 네비게이션이 VC를 강한 참조로 들고 있는 상황인데.. 코디네이터가 뷰가 사라지면 왜 자동 할당해제돼..? 예제하나 보여줄 수 있어? 블로그랑 저 사진봤는데도 이해가 안가네 (저 사진 화살표방향이 잘못된듯. 참조하는 방향으로 화살표가 되어야하는데?)

```swift
class MainCoordinator: Coordinator {
    private weak var navigationViewController: UINavigationController?
    
    func start() { ... }
}

extension Coordinator: ViewModelDelegate { ... }
```

2022-10-13 05:29 UTC, LentoAssai commented
>저블로그가 소개하는 방식이 이해가 가지 않는데 코디네이터는 VC를 들고 있을텐데 왜 view가 없어지면 자동으로 할당해제되는거지? 아래 코디네이터에는 네비게이션 인스턴스를 약한 참조하고 있고, 네비게이션이 VC를 강한 참조로 들고 있는 상황인데.. 코디네이터가 뷰가 사라지면 왜 자동 할당해제돼..? 예제하나 보여줄 수 있어? 블로그랑 저 사진봤는데도 이해가 안가네 (저 사진 화살표방향이 잘못된듯. 참조하는 방향으로 화살표가 되어야하는데?)

Coordinator가 navigationController를 약한참조 하고있고, navigationController에 viewControllers들이 있어서 강한참조 하고, 각 viewControllers들은 viewModels를 강한참조하고, 각 viewModel에 coordinator들이 강한참조로 들어있으니까 navigationController에 있는 viewControllers들이 다 pop되어서 할당 해제되면 모든 viewModel이 할당해제되고, viewModel이 강한 참조하고 있던 coordinator도 할당해제되는걸로 이해했어.

블로그에서도 아래와 같이 얘기를 했었고.
>Note that if this is the last view model that was holding the coordinator, the coordinator gets automatically released too without any extra effort or callbacks that was needed using child coordinators.

화살표 방향은 참조를 받는 곳으로 향해야하는거면 반대로 된거같네.

예제는 블로그에 나와있는 [예제](https://github.com/AlbertMontserrat/CoordinatorsAutoHandled)보면 될듯

2022-10-13 05:32 UTC, LentoAssai commented
>지금 이 말이 살짝 이해가 안가. Coordinator는 화면전환인데 다른 사람들도 화면전환 코드를 다뤄야하기 때문에 각각의 피쳐에 포함시키는거야. 한사람이 관리하면 충돌은 안나겠지만(이 충돌도 눈으로 보이기때문에 해결하기 쉬움), 동기적으로 작업이 되기 때문에 시간이 더 오래 걸려. 따라서, 각자가 작업하기 위해서 각 피쳐 폴더 안에 넣는거야 그리고 위에 단점 몇가지를 더 적어놨어. 너가 생각하는 화면전환을 따로 폴더를 만들어서 관리하는 장점이 뭘까?

말했듯이 내가 coordinating 작업을 다 맡아서 할거같아서 폴더를 빼놨어. 다른 사람들은 이 폴더 잘 안볼거같아서.
그냥 각자의 Flow 안에서 다음 화면으로 넘어가는 등의 coordinating 인터페이스만 만들어놓고 코드 작성해놓으면 내가 연결할 생각이었어서 이렇게 했어

근데 그게 아니고 다른 사람들도 화면 전환 관련한 코드를 다루고, 충돌이 나더라도 비교적 간단하게 해결 가능하고, 너가 말한 추후에 모듈화 등등을 생각해보면 각 feature폴더에 넣는게 좋을거같네

2022-10-13 05:36 UTC, wody-d commented
디코 고?

2022-10-13 05:37 UTC, LentoAssai commented
지금 ㅇㄷ?

2022-10-13 05:38 UTC, wody-d commented
> 지금 ㅇㄷ?

도서관. 이따 애형님이랑 카페갈듯

2022-10-13 05:42 UTC, luminouxx reviewed
## 고생했습니다 찰리!

+ 몇가지 의문점이 생겨 코멘트를 달게 되었습니다.

### 1. Coordinator 패턴을 적용한 이유가 뭘까요?
> 만약, 단지 화면전환의 용이성이 목적이었다면, 저는 위와 같은 코드도 괜찮다고 생각합니다.
> 하지만, 화면 전환간의 계층구조를 확실하게 구현하지는 못할 것 같군요
>> 왜냐하면 Main Coordinator에서 하위 coodinator를 관리할 수 없지 않나 싶습니다.
> 만약 그렇다고 한다면, Parents&child 구조를 택하는 것이 좋아보입니다.

### 참조에 대한 이야기는 우디와의 코멘트를 읽어보겠습니다.

2022-10-13 06:42 UTC, LentoAssai commented on Sources/App/AppDelegate.swift
> +
how intriguing!

2022-10-13 07:31 UTC, wody-d commented
### 정리 

```swift 
class 뷰모델 {
    let 코디: 코디네이터
    init(코디: 코디네이터) {
        self.코디 = 코디
    }
}

class 코디네이터 {
    weak var navigation: UINavigationController?
}

class 뷰컨트롤러 {
    let 뷰모델: 뷰모델
    init(뷰모델: 뷰모델) {
        self.뷰모델 = 뷰모델
    }
}
```

2022-10-13 07:32 UTC, LentoAssai commented
> 만약, 단지 화면전환의 용이성이 목적이었다면, 저는 위와 같은 코드도 괜찮다고 생각합니다.
하지만, 화면 전환간의 계층구조를 확실하게 구현하지는 못할 것 같군요
여기서 위와 같은 코드가 뭔지 모르겠네영

일단 parent&child를 쓰지 않은 이유는 child가 끝날 때 parent에 알리고, parent에서 해당 child를 찾아서 삭제하고 이런 boiler plate 코드들을 없애는게 가장 큰 목적입니다
parent에서 child를 가지지 않아서 따로 관리를 할 수는 없지만, 따로 관리할 필요도 없을 것 같아서 과감하게 이 방법을 채택했습니다.
가령, child의 flow 실행중에 parent로 가서 실행중인 child를 어떻게 해달라는 등의 요청은 앱 실행 도중에 일어나지 않을 것 같습니다

도움이 되셨나요?
도움이 되셨다면 구독과 좋아요, 알림설정 부탁드려요~

2022-10-13 07:33 UTC, LentoAssai commented on Sources/Coordinator/Main/MainCoordinator.swift
> +    var tabBarItems: [TabBarItem] = [ .home, .search, .feed, .profile]
EASY

2022-10-13 08:54 UTC, wody-d approved these changes
반영이 빠르네 🤚🏻

2022-10-13 08:54 UTC, LentoAssai commented
>지금 이 말이 살짝 이해가 안가. Coordinator는 화면전환인데 다른 사람들도 화면전환 코드를 다뤄야하기 때문에 각각의 피쳐에 포함시키는거야. 한사람이 관리하면 충돌은 안나겠지만(이 충돌도 눈으로 보이기때문에 해결하기 쉬움), 동기적으로 작업이 되기 때문에 시간이 더 오래 걸릴 거 같아서 각자 편하게 작업하기 위해서 피쳐 폴더 안에 넣는 의도로 생각했어 그리고 위에 단점 몇가지를 더 적어놨어. 너가 생각하는 화면전환을 따로 폴더를 만들어서 관리하는 장점이 뭘까?

디렉토리 변경 : [21a143c](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Trying-iOS/pull/13/commits/21a143c9af6a6e998eb0a2a11aa23a426ca6abea)

2022-10-13 10:49 UTC, luminouxx approved these changes
그렇다면 알겠습니다 과감하군요 과감찰리

2022-10-13 15:44 UTC, merged

2022-10-14 04:56 UTC, kyustudyo commented
와우 코디네이터 패턴을 알게되어서 기쁩니다! 좋은 디자인패턴 들고와주셔서 감사하고 공부해서 도움이 되도록 노력하겠습니다!