✨ Log탭에서 코스의 리뷰를 불러오는 API연동
DeveloperAcademy-POSTECH/MacC-Team-Trying-iOS pull request #171
Opened 2022-11-18 14:38 UTC by luminouxx

## 🔍 개요
+ #170 

## 📝 작업사항

### 1. FetchReview API 연동
- FetchReviewDTO.swift
- FetchReviewRepositoryImpl.swift
- FetchReviewRepository.swift
- FetchReviewUseCase.swift
> 4개의 작업을 완료했습니다.
> 클린 아키텍처를 참고했습니다.
> 질문하고 싶은 것이 있습니다.

#### DTO -> Entity 함수
```swift
private func convertToReviewEntity(_ responseData: FetchReviewDTO) -> [ReviewEntity] {
        
        var reviews = [ReviewEntity]()
        let emptyReview = ReviewEntity(name: "", imagesURL: [], content: "")
        
        if let myReview = responseData.myReview {
            let myReviewEntity = ReviewEntity(
                name: myReview.writerName,
                imagesURL: myReview.images,
                content: myReview.content
            )
            reviews.append(myReviewEntity)
        } else {
            reviews.append(emptyReview)
        }
        
        if let mateReview = responseData.mateReview {
            let mateReviewEntity = ReviewEntity(
                name: mateReview.writerName,
                imagesURL: mateReview.images,
                content: mateReview.content
            )
            reviews.append(mateReviewEntity)
        } else {
            reviews.append(emptyReview)
        }
        return reviews
    }
```
DTO는 내리뷰, 메이트리뷰를 받아옵니다.
Entity로 변환하는 과정에서 nil을 바로 떄려넣는 것은 
뭔가 조금 위험한 것 같다는 생각이 들어서
if let 구문에서 nil을 판단한 후, 깡통 데이터를 넣어주는 방식을 택했는데, 어떨지 궁금합니다.
결과로 크기가 2인 [ReviewEntity]가 반환되고 
0번 인덱스는 나의 리뷰
1번 인덱스는 상대방의 리뷰로 지정했는데 괜찮을까요?

### 2. FetchLog API 수정
> 추가로 #160 PR의 내용을 조금 수정했습니다. DTO가 바뀌었습니다. 
> 이번에 수정을 하면서 아키텍처의 장점을 알 수 있어서 좋은 경험이었습니다.

### 3. ReviewEntity 수정
> ReviewEntity는 저밖에 쓰지 않는 것 같아서 수정을 했습니다. (실제로 쓰는, 제 나름 Entity에 가장 가까운 방향)
> 공유를 해야한다면 이 내용을 공유해주세요 @LentoAssai 
```swift
 import Foundation

struct ReviewEntity {
    //let id: Int  : 필요없어서 삭제
    //let author: UserEntity : 필요없어서 삭제
    let name: String
    var imagesURL: [String]
    let content: String
}
```

## 📸 스크린샷 또는 영상

<img width="567" alt="스크린샷 2022-11-18 오후 11 15 01" src="https://user-images.githubusercontent.com/81943525/202726920-22ddd799-243b-4fef-a877-96f45ad0030f.png">

+ ViewModel에서의 테스트입니다.

<img width="732" alt="스크린샷 2022-11-18 오후 11 18 09" src="https://user-images.githubusercontent.com/81943525/202726886-cb4fa14a-b109-419b-ac6d-d38fe46ce425.png">

## 🧐 참고 사항

+ 질문 사항들을 읽어주시면 감사하겠습니다.

2022-11-18 14:46 UTC, LentoAssai commented
> Entity로 변환하는 과정에서 nil을 바로 떄려넣는 것은
뭔가 조금 위험한 것 같다는 생각이 들어서

여기서 왜 위험할 것 같다고 생각하셨나요??

2022-11-18 14:56 UTC, LentoAssai requested changes

2022-11-18 14:56 UTC, LentoAssai commented on Sources/Data/Log/FetchConstellation/FetchConstellationDTO.swift
>          let liked: Bool
볼때마다 걸렸던건데 `liked`를 `isLiked`로 고치고 codingKey 활용하는건 어떨까요?

2022-11-18 14:56 UTC, LentoAssai commented on Sources/Data/Log/FetchConstellation/FetchConstellationRepositoryImpl.swift
> +                    address: "",
빈 문자열로 하신 이유가??

2022-11-18 14:56 UTC, LentoAssai commented on Sources/Data/Log/FetchReview/FetchReviewRepositoryImpl.swift
> +        }
nil이 아닌 빈 reviewEntity로 하면 위험하다고 생각하신 이유가 궁금합니당

2022-11-18 14:56 UTC, LentoAssai commented on Sources/Domain/Log/FetchReview/FetchReviewUseCase.swift
> +    }
이거 아직 헷갈리네요 ㅋㅋ
RepositoryImpl을 여기서 주입시키는게 클린 아키텍쳐에 부합하는걸까요??

도메인영역에서는 impl을 알면 안되기때문에 저는 안된다고 생각이 들어용

2022-11-18 14:59 UTC, luminouxx commented on Sources/Data/Log/FetchConstellation/FetchConstellationRepositoryImpl.swift
> +                    address: "",
이제 API가 주소를 안줘요

2022-11-19 10:43 UTC, luminouxx commented on Sources/Data/Log/FetchReview/FetchReviewRepositoryImpl.swift
> +        }
Entity의 Property는 NULL을 받지 않는 것이 일반적인 것으로 알고 있습니다.
그 이유는
+ 반환값으로 null 을 return 받는 경우, 추후 null을 반환해준 라인과는 상관없는 코드에서 null pointer Exception이 터질 수 있어서 트래킹이 어렵다.
+ 즉, 예외 발생 시 예외 스택 전체를 캡쳐하는 비용을 아낄 수 있음
+ 빈 타입 객체가 들어 있는 경우, Optional에서 정의된 method 등을 이용하여, 좀 더 유연한 핸들링이 가능함

2022-11-19 10:45 UTC, luminouxx commented on Sources/Data/Log/FetchReview/FetchReviewRepositoryImpl.swift
> +        }
즉 빈 배열인 경우보다 nil일 경우가 예상하지 못한 에러가 터질 확률이 높고, 고려할 케이스가 많다는 이야기 입니다.

2022-11-19 10:49 UTC, luminouxx commented on Sources/Domain/Log/FetchReview/FetchReviewUseCase.swift
> +    }
Architecture의 설계의 목표 자체가 역할을 분리하기 위함이고
Repository의 구현체 부분이 UseCase를 참조하고 있지 않기 떄문에 큰 문제가 되지 않는다고 생각합니다.

2022-11-19 11:14 UTC, LentoAssai approved these changes

2022-11-19 11:38 UTC, merged