✨코스 등록에 필요한 기본 컴포넌트 구현 (Button, TextField, NavigationBar)
DeveloperAcademy-POSTECH/MacC-Team-Trying-iOS pull request #38
Opened 2022-10-15 13:18 UTC by LentoAssai

## 🔍 개요
#28 코스 등록 과정에서 필요한 컴포넌트 구현

## 📝 작업사항
- Asset을 추가하였습니다. 
  - chevron_left 이미지
  - x_mark 이미지
  - Colors
- 버튼을 구현하였습니다.
  - MainButton
  - SmallRectButton
  - SmallRoundButton
- TextField, TextView를 구현하였습니다.
  - CustomTextField
  - CustomTextView
- NavigationBar를 구현하였습니다.
- Constants에 몇가지 상수를 추가하였습니다.
  - Screen -> 현재 스크린의 width, height
  - Image -> 이미지 파일 이름
- TestViewController를 수정하여 테스트했습니다.
- BaseViewController에서 StatusBarStyle을 `.lightContent`로 설정하였습니다.

## 📸 스크린샷 또는 영상

| MainButton | SmallButton | NavigationBar | TextField, TextView |
|-----|-----|-----|-----|
| <img src="https://user-images.githubusercontent.com/88371913/195981493-386fccb5-4ce5-4b65-a1fe-101ab35c7942.png" width="250"> | <img src="https://user-images.githubusercontent.com/88371913/195981512-f8c76538-43ff-495e-b439-3e8e1724ebab.png" width="250"> | <img src="https://user-images.githubusercontent.com/88371913/195981544-15dbb9e3-6284-469f-a038-6b72ade6b0da.png" width="250"> | <img src="https://user-images.githubusercontent.com/88371913/195981553-1b968ad2-0b31-484f-ad50-1b8ee6fb534f.png" width="250"> |

2022-10-15 15:16 UTC, wody-d requested changes
## 찰리 수고하셨습니다.
> 루미 방식이 좋아보여 따라함

지금 만든 버튼, 네비게이션바, 텍스트필드들은 디자인시스템의 요소들이야? 아니면 너만 사용하는 것들이야? 컴포넌트들의 크기들이 모두 각 컴포넌트에서 해결이 되는데, 그러면 외부에서 가져다가 쓰려고 해도 조절을 할 수가 없게 되서 문제가 될거같아. 모두 외부에서 레이아웃을 잡아줄 수 있도록 수정해주면 좋을 것 같아~
그리고 네비게이션바를 커스텀했는데 그래야하는 이유를 모르겠어 우리 네비게이션바가 HIG를 어기지 않았는데 기본 네비게이션바를 사용하면 되는 거 아닐까? 커스텀한 의도를 알 수 있을까? 
마지막으로, 남들이 사용할 것들에는 DocC달아줘~

2022-10-15 15:16 UTC, wody-d commented on Sources/Presenter/Home/AddCourse/Components/Button/SmallRoundButton.swift
> +    }
비율대로 의도한 건 좋은데 버튼의 가로:세로 비율대로 맞추는게 더 좋은 방법같아

2022-10-15 15:16 UTC, wody-d commented on Sources/Presenter/Home/AddCourse/Components/TextField/CustomTextField.swift
> +            }
이것들도.. 음 이거 애셔가 비율을 이렇게맞추라고 한거야? 아니면 너가 임의대로 작성한거야? 
만약 이상태로간다면 디바이스별로 서치바가 다르게 나올거같은데? 일정하게 나온다고해도, 우리가 높이와 너비를 추론할 수가 없게되서 레이아웃하기 어려워질거같아

2022-10-15 15:16 UTC, wody-d commented on Sources/Utility/Extensions/UIView+.swift
> +    }
docC 추가부탁해~

2022-10-15 15:16 UTC, wody-d commented on Sources/Utility/Extensions/UIButton+.swift
> +    }
docC 추가부탁해~

2022-10-15 15:16 UTC, wody-d commented on Sources/Utility/Constants/Constants.swift
> +    }
이건 상수인가? 아니면 디바이스별로 바뀌는 변수인가? 
이 Constants 파일에 들어갈 만한 요소인가? 우리가 직접 지정한 상수가 아닌 디바이스 정보를 이파일에 넣어도될까? 이런 고민이 있는데 너의 결론은 함게 넣어도된다? (질문)

2022-10-15 15:47 UTC, LentoAssai commented on Sources/Presenter/Home/AddCourse/Components/Button/SmallRoundButton.swift
> +    }
음 무슨말인지 이해가 안되네

2022-10-15 15:50 UTC, wody-d commented on Sources/Presenter/Home/AddCourse/Components/Button/SmallRoundButton.swift
> +    }
버튼의 크기가 가로:세로 = 2:1 이라면 버튼의 가로세로 비율을 맞추는게 디자인을 해치지않는거같아 지금형태로라면 소수점단위로 버튼의 너비와 높이가 정해지는거같아

2022-10-15 15:54 UTC, wody-d commented on Sources/Presenter/Home/AddCourse/Components/TextField/CustomTextField.swift
> +            }
다른 디바이스는 390, 844가 아닐텐데? 그럼 원래 컴포넌트는 가로세로가 90,30이니까 비율은 3:1인데 가로 세로가 비율이 달라지는 디바이스의 경우 컴포넌트의 크기는 3:1이 깨져. 애셔가 지난번에 두가지 방법을 알려준거같은데 그게 아래랑 같아. 이거 애셔한테 컴포넌트 크기는 물어봐서 진행한거야? 

1. 높이는 일정, 너비만 기기별로 변동(마진으로설정)
2. 버튼의 비율을 고정 (3:1)

2022-10-15 16:01 UTC, LentoAssai commented on Sources/Presenter/Home/AddCourse/Components/TextField/CustomTextField.swift
> +            }
위에 conversation이랑 같이 얘기하자

아하 난 90/390, 30/844하면 비율이 나오니까 이걸 기기별 가로 세로 값에 곱해주면 기기대응 될거라고 생각햇어

근데 컴포넌트마다 너가 말한거처럼 세로는 고정하고 가로는 변하게, 비율을 고정해서 등등 그냥 단순히 화면이 커진다고해서 똑같이 커지고 이런게 아니니까 물어보고 수정해야겠네

2022-10-15 16:07 UTC, LentoAssai commented on Sources/Utility/Constants/Constants.swift
> +    }
오... 철학적인 질문이다
개발하는 입장에서는 여러 기기가 있을 수 있으니까 디바이스별로 바뀌는 변수라고 말할 수 있을거같고
앱의 입장에서는 상수인듯? ㅋㅋㅋㅋ
그냥 말장난이고
난 작성한 코드처럼 컴포넌트 크기들 기기대응할 때 UIScreen.main.bounds 많이 쓰니까 (다른 상황에서 사용할 때도) 이런게 있으면 좋을거같다는 생각이었고 Constants에 같이 작성했어

직접 지정한 상수는 아니여서 정확히 말하면 Constants에 있는게 어색하긴 하지만
내가 생각했던 Constants는 string을 입력할 때 오타가 나거나, 자주 사용하는 것들을 쉽게 접근할 수 있도록 하는 등의 편의성을 주고자했었어

2022-10-15 16:17 UTC, LentoAssai commented on Sources/Utility/Extensions/UIView+.swift
> +    }
[029ef8e](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Trying-iOS/pull/38/commits/029ef8e1fc66915596692194eafa33d74024811f)

2022-10-15 16:17 UTC, LentoAssai commented on Sources/Utility/Extensions/UIButton+.swift
> +    }
[029ef8e](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Trying-iOS/pull/38/commits/029ef8e1fc66915596692194eafa33d74024811f)

2022-10-15 16:20 UTC, LentoAssai commented
>지금 만든 버튼, 네비게이션바, 텍스트필드들은 디자인시스템의 요소들이야? 아니면 너만 사용하는 것들이야? 컴포넌트들의 크기들이 모두 각 컴포넌트에서 잡혀있는데 그러면 외부에서 가져다가 쓰려고 해도 조절을 할 수가 없게 되서 문제가 될거같아. 모두 외부에서 레이아웃을 잡아줄 수 있도록 수정해주면 좋을 것 같아~

일단 내가 맡은 플로우에서 사용하는 컴포넌트들만 만들었는데, 아마 다른 화면에서도 사용하는게 있으면 재사용할 수 있을거같아.
컴포넌트 크기는 각 화면에서 잡는게 나으려나? 다른 화면에서도 완전히 같은 사이즈만을 사용하면 컴포넌트 안에서 잡는게 편하지 않을까?
난 그렇게 생각해서 컴포넌트 안에서 사이즈를 잡아놓은 상태이구, 다른 화면들에서 같은 형태의 컴포넌트를 사용하는데 사이즈만 다르다 하면 그 때 수정하는게 낫지 않을까?

2022-10-15 16:21 UTC, wody-d commented on Sources/Utility/Constants/Constants.swift
> +    }
옹 그럼 디바이스 width와 height는 개발 편의성을 위한 유틸과 같은 개념이라고 생각한거네?
개발자가 지정하는 string이 아니니까 다르게 구분해도 좋을듯. `DeviceInfo`와 같은 파일로 따로 구분해도 될 듯. 여기 있기에 좀 어색하네

2022-10-15 16:22 UTC, wody-d commented on Sources/Presenter/Home/AddCourse/Components/Button/SmallRoundButton.swift
> +    }
> > 지금 만든 버튼, 네비게이션바, 텍스트필드들은 디자인시스템의 요소들이야? 아니면 너만 사용하는 것들이야? 컴포넌트들의 크기들이 모두 각 컴포넌트에서 잡혀있는데 그러면 외부에서 가져다가 쓰려고 해도 조절을 할 수가 없게 되서 문제가 될거같아. 모두 외부에서 레이아웃을 잡아줄 수 있도록 수정해주면 좋을 것 같아~
> 
> 일단 내가 맡은 플로우에서 사용하는 컴포넌트들만 만들었는데, 아마 다른 화면에서도 사용하는게 있으면 재사용할 수 있을거같아. 컴포넌트 크기는 각 화면에서 잡는게 나으려나? 다른 화면에서도 완전히 같은 사이즈만을 사용하면 컴포넌트 안에서 잡는게 편하지 않을까? 난 그렇게 생각해서 컴포넌트 안에서 사이즈를 잡아놓은 상태이구, 다른 화면들에서 같은 형태의 컴포넌트를 사용하는데 사이즈만 다르다 하면 그 때 수정하는게 낫지 않을까?

버튼 사이즈가 고정이야? 난 너비는 동적으로 변한다고 생각했는뎅

2022-10-15 16:23 UTC, wody-d commented
> > 지금 만든 버튼, 네비게이션바, 텍스트필드들은 디자인시스템의 요소들이야? 아니면 너만 사용하는 것들이야? 컴포넌트들의 크기들이 모두 각 컴포넌트에서 잡혀있는데 그러면 외부에서 가져다가 쓰려고 해도 조절을 할 수가 없게 되서 문제가 될거같아. 모두 외부에서 레이아웃을 잡아줄 수 있도록 수정해주면 좋을 것 같아~
> 
> 일단 내가 맡은 플로우에서 사용하는 컴포넌트들만 만들었는데, 아마 다른 화면에서도 사용하는게 있으면 재사용할 수 있을거같아. 컴포넌트 크기는 각 화면에서 잡는게 나으려나? 다른 화면에서도 완전히 같은 사이즈만을 사용하면 컴포넌트 안에서 잡는게 편하지 않을까? 난 그렇게 생각해서 컴포넌트 안에서 사이즈를 잡아놓은 상태이구, 다른 화면들에서 같은 형태의 컴포넌트를 사용하는데 사이즈만 다르다 하면 그 때 수정하는게 낫지 않을까?

버튼 사이즈가 고정이야? 난 너비는 동적으로 변한다고 생각했는뎅

2022-10-15 16:23 UTC, LentoAssai commented
>그리고 네비게이션바를 커스텀했는데 그래야하는 이유를 모르겠어 우리 네비게이션바가 HIG를 어기지 않았는데 기본 네비게이션바를 사용하면 되는 거 아닐까? 커스텀한 의도를 알 수 있을까?

내가 UINavigationBar를 커스텀 안해봐서 얼마나 가능한지 몰랐어
<img width="261" alt="스크린샷 2022-10-16 01 21 31" src="https://user-images.githubusercontent.com/88371913/195997135-815a4307-d2a3-4f26-ae55-1ba0436e6855.png">

이런 NavigationBar를 만들어야 하는데 UINavigationBar보다 그냥 UIView로 그리는게 편해서(?) 이렇게 했어

UINavigationBar로 바꿀까??

2022-10-15 16:24 UTC, wody-d commented
> > 그리고 네비게이션바를 커스텀했는데 그래야하는 이유를 모르겠어 우리 네비게이션바가 HIG를 어기지 않았는데 기본 네비게이션바를 사용하면 되는 거 아닐까? 커스텀한 의도를 알 수 있을까?
> 
> 내가 UINavigationBar를 커스텀 안해봐서 얼마나 가능한지 몰랐어 <img alt="스크린샷 2022-10-16 01 21 31" width="261" src="https://user-images.githubusercontent.com/88371913/195997135-815a4307-d2a3-4f26-ae55-1ba0436e6855.png">
> 
> 이런 NavigationBar를 만들어야 하는데 UINavigationBar보다 그냥 UIView로 그리는게 편해서(?) 이렇게 했어
> 
> UINavigationBar로 바꿀까??

기본 네비게이션이 주는 애니메이션을 포기할 정도로 현재 디자인된 네비게이션바가 커스텀정도가 그렇게 어렵다고 생각하지 않아~ UINavigationBar로 바꾸면 좋을듯!

2022-10-15 16:26 UTC, LentoAssai commented on Sources/Utility/Constants/Constants.swift
> +    }
오 조아

2022-10-15 16:32 UTC, LentoAssai commented on Sources/Utility/Constants/Constants.swift
> +    }
[dac29f8](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Trying-iOS/pull/38/commits/dac29f8c204b3f258f7c2d3d6b99a8b4fc80a926)

2022-10-15 16:36 UTC, LentoAssai commented
>버튼 사이즈가 고정이야? 난 너비는 동적으로 변한다고 생각했는뎅

동적으로 변한다는게.. 버튼의 title이 길어지면 늘어난다는건가? 아님 디바이스가 커지면 늘어난다는건가?
후자라면 내가 작성한 코드로도 동적으로 변하는거지 않아?
전자는 일단 내가 맡은 뷰들에서는 고정되어 있어서 괜찮을 것 같고, 만약 다른 뷰에서 재사용을 하고 동적으로 변해야 한다면 위에 말했듯이 컴포넌트 안에서 크기를 정하는게 아니라 해당 뷰에서 정할 수 있도록 수정할게

2022-10-15 16:42 UTC, wody-d commented
> > 버튼 사이즈가 고정이야? 난 너비는 동적으로 변한다고 생각했는뎅
> 
> 동적으로 변한다는게.. 버튼의 title이 길어지면 늘어난다는건가? 아님 디바이스가 커지면 늘어난다는건가? 후자라면 내가 작성한 코드로도 동적으로 변하는거지 않아? 전자는 일단 내가 맡은 뷰들에서는 고정되어 있어서 괜찮을 것 같고, 만약 다른 뷰에서 재사용을 하고 동적으로 변해야 한다면 위에 말했듯이 컴포넌트 안에서 크기를 정하는게 아니라 해당 뷰에서 정할 수 있도록 수정할게

후자야
너꺼도 동적으로 변하고 있지 근데 위에서도 말했듯이 얖옆마진은 일정치 않을거야. 예를 하나 들어볼게
현재 디바이스의 너비가 10이고 양 옆 마진이 2,2인 버튼 있어. 이 경우 버튼의 너비는 6이될거야 근데 넌 지금 6/10 = 0.6을 디바이스 너비에 곱해준 상황이야. 극단적으로 생각하면 이제 디바이스의 너비가 11이 됐어. 11 * 0.6 = 6.6이 버튼의 너비가 될 텐데 그럼 양 옆 마진 2.2, 2.2가 되기 때문에 양 옆 마진 2, 2를 유지하지 못해. 또한 버튼의 크기가 너무 동적으로 변하기 때문에 다른 컴포넌트의 레이아웃을 잡기에도 불편하고 소수점을 가지고 레이아웃을 구성하게돼 단점투성이 아닐까?

2022-10-15 16:46 UTC, LentoAssai commented
>후자야 너꺼도 동적으로 변하고 있지 근데 위에서도 말했듯이 얖옆마진은 일정치 않을거야.
예를 하나 들어볼게.
현재 디바이스의 너비가 10이고 양 옆 마진이 2,2인 버튼 있어. 이 경우 버튼의 너비는 6이될거야 근데 넌 지금 6/10 = 0.6을 디바이스 너비에 곱해준 상황이야. 극단적으로 생각해서 디바이스의 너비를 11이라고 생각해보자. 11 * 0.6 = 6.6이 버튼의 너비가 될 텐데 그럼 양 옆 마진 2.2, 2.2가 되기 때문에 양 옆 마진 2, 2를 유지하지 못해. 또한 버튼의 크기가 너무 동적으로 변하기 때문에 다른 컴포넌트의 레이아웃을 잡기에도 불편하고 소수점을 가지고 레이아웃을 구성하게돼 단점투성이 아닐까?

눈높이 교육 감사합니다~
구독, 좋아요 누르고 갈게요

2022-10-15 16:47 UTC, wody-d commented
좋아요 먹튀하네 ㅡㅡ

2022-10-16 05:27 UTC, LentoAssai commented
UINavigationBar로 바꾸려는 몇번의 시도 끝에
1) NavigationBar가 달라지는 View마다 새로 커스텀한 UINavigationBar를 설정해주고, 이전에 쌓여있던 ViewControllers들을 새로운 NavigationBar에 할당하는 방법
2) ViewController마다 `setNavigationBar()` 메소드를 호출해서 각자의 NavigationBar를 그리게 하는 방법
이 가능할 것 같은데,

1번은 계속 NavigationBarFactory 등을 통해서 미리 만들어둔다고 쳐도 계속 NavigationBar를 갈아 끼워줘아하고 그 과정에서 ViewControllers 들을 다시 할당해줘야해서 번거로워 보임

그래서 `BaseViewController`에 `setNavigationBar()` 메소드를 추가해놓고, ViewController마다 NavigationBar를 설정해주도록 하려고 하는데 어때?

2022-10-16 05:34 UTC, LentoAssai commented
그리고 HIG에 크게 위배되지 않으니까 기본 제공하는 NavigationBar를 쓰는게 좋아보인다고 말했줬는데,
커스텀해서 UIView로 하는거보다 좋은점이 뭐가 있을까? 내가 생각했을 때는 기본적으로 제공하는 기능들(예를들어 back button 꾹 누르면 stack에 있는 view들 나타나는거)을 사용할 수 있는거라고 생각하는데, 별로 필요 없을 것 같아서 굳이 NavigationBar를 설정해서 보여줘야하는지 잘 모르겠어. 어디까지나 나는 UIView로 NavigationBar를 만들고 그걸 보여주는게 편한 사람으로서.

2022-10-16 06:12 UTC, LentoAssai commented
음.. 그리고 UIBarButtonItem은 View class가 아니라서 constraints도 어떻게 잡아야하는지 모르겠다 ㅠㅠ

2022-10-16 06:30 UTC, LentoAssai commented on Sources/Presenter/Home/AddCourse/Components/TextField/CustomTextField.swift
> +            }
[5699679](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Trying-iOS/pull/38/commits/5699679825b1a5f1f5e80e08ff528146c3437f31)

너비만 바뀔거라고 얘기를 들어서 일단 지금 컴포넌트들에 대해서는 대부분 높이만 컴포넌트에서 설정하고, 너비는 ViewController에서 잡도록 변경했어

2022-10-16 06:33 UTC, LentoAssai commented
버튼 사이즈에 대해서는 [5699679](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Trying-iOS/pull/38/commits/5699679825b1a5f1f5e80e08ff528146c3437f31) 커밋에서 해결해놨고,

NavigationBar만 어떻게 할지 처리하고 PR 마무리 하겠습니다.

2022-10-17 06:54 UTC, kyustudyo approved these changes

2022-10-17 06:54 UTC, kyustudyo commented on Sources/Presenter/Home/AddCourse/Components/TextField/CustomTextField.swift
> +        self.leftViewMode = .always
UITextField의 leftView, leftViewModel 처음 보았습니다. 신기하네요!

2022-10-17 06:54 UTC, kyustudyo commented on Sources/Presenter/Home/AddCourse/Components/TextField/CustomTextField.swift
> +                make.width.equalTo(DeviceInfo.Screen.width * 0.7948)
저도 DeviceInfo를 얼른 쓰고싶네요.

2022-10-17 06:54 UTC, kyustudyo commented on Sources/Presenter/Profile/ProfileTestViewController.swift
> +        view.addSubviews(textField1, textField2, textField3, textField4, textView)
addSubviews 잘 쓰겠습니다~

2022-10-17 06:56 UTC, LentoAssai commented on Sources/Presenter/Home/AddCourse/Components/TextField/CustomTextField.swift
> +        self.leftViewMode = .always
UITextField에 이미지 넣을 때 자주 사용합니다
rightView도 있으니 찾아보시면 나중에 꼭 도움될 듯 하네용

2022-10-17 06:57 UTC, LentoAssai commented on Sources/Presenter/Home/AddCourse/Components/TextField/CustomTextField.swift
> +                make.width.equalTo(DeviceInfo.Screen.width * 0.7948)
개봉박두

2022-10-17 06:57 UTC, LentoAssai commented on Sources/Presenter/Profile/ProfileTestViewController.swift
> +        view.addSubviews(textField1, textField2, textField3, textField4, textView)
👍

2022-10-17 08:39 UTC, wody-d commented
> 그리고 HIG에 크게 위배되지 않으니까, 그리고 애니메이션을 쓸 수 있어서 기본 제공하는 NavigationBar를 쓰는게 좋아보인다고 말했줬는데,
> (btw, 기본 제공해주는 애니메이션이 뭐지...? 뒤로가기 스와이프 말하는건가?)
> 커스텀해서 UIView로 하는거보다 좋은점이 뭐가 있을까? 내가 생각했을 때는 기본적으로 제공하는 기능들(예를들어 back button 꾹 누르면 stack에 있는 view들 나타나는거)을 사용할 수 있는거라고 생각하는데, 별로 필요 없을 것 같아서 굳이 NavigationBar를 설정해서 보여줘야하는지 잘 모르겠어. 어디까지나 나는 UIView로 NavigationBar를 만들고 그걸 보여주는게 편한 사람으로서.

음.. 그럼 HIG가 왜 있을까? 편한 방식으로 개발하면되는데.
왜 컨벤션을 정할까? 있으면 불편하기만한데.
애니메이션은 너가 말한 것도 있고 화면전환될때, 네비게이션바에서 left item과 right item이 애니메이션이 돼

2022-10-17 08:44 UTC, wody-d commented
그리고 이 피알은 왜 files change가 58개임?

2022-10-17 08:45 UTC, LentoAssai commented on Sources/Utility/DeviceInfo/DeviceInfo.swift
> +    }
디바이스인포에 다른 정보도 들어갈 수 있을거같아서

2022-10-17 08:46 UTC, wody-d commented on Sources/Utility/DeviceInfo/DeviceInfo.swift
> +    }
예를들어!?

2022-10-17 08:48 UTC, LentoAssai commented on Sources/Utility/DeviceInfo/DeviceInfo.swift
> +    }
생각해보니 딱히 들어갈거 없네

2022-10-17 08:49 UTC, LentoAssai commented on Sources/Utility/DeviceInfo/DeviceInfo.swift
> +    }
수정 커밋 : [8fc579a](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Trying-iOS/pull/38/commits/8fc579ae69e70c6b06c27d06147dfabb78ffc302)

2022-10-17 08:53 UTC, LentoAssai commented
NavigationBar UINavigationBar로 만들고 다시 push하겠습니다.

2022-10-17 09:43 UTC, wody-d commented
> 음.. 그리고 UIBarButtonItem은 View class가 아니라서 constraints도 어떻게 잡아야하는지 모르겠다 ㅠㅠ

이거 UIBarButtonItem의 inset으로 주면될걸?!

2022-10-17 13:45 UTC, wody-d commented
> UIView로 구현한 NavigationBar 삭제,
> NavigationBarConfigurable 프로토콜을 통한 NavigationBar 설정 메소드 구현
> [e4edb88](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Trying-iOS/pull/38/commits/e4edb889da503f4887a833c7eb18b1391cd4696d)

음 이 pr은 내일 세션 때 더 이야기를 나누어봐야할거같은데 어케 생각해? (오늘말고 내일로 기한 미루자)

2022-10-17 14:00 UTC, LentoAssai commented
ㅇㅇ

2022-10-17 14:08 UTC, wody-d commented
어푸룹해줄게 머지하셈

2022-10-17 14:10 UTC, LentoAssai commented
엥?? 얘기할거 잇다면서

2022-10-17 14:14 UTC, wody-d approved these changes

2022-10-18 02:00 UTC, merged