Feat/10 configure coure feed
DeveloperAcademy-POSTECH/MacC-Team-Trying-iOS pull request #59
Opened 2022-10-20 15:54 UTC by luminouxx

## 🔍 개요
- #10 

## 📝 작업사항
- 피드 첫번째 뷰 UI구성
- 마땅한 mockup이 없어 테스트 모델을 썼습니다.
- 아직 애니메이션은 안넣었습니다.

## 📸 스크린샷 또는 영상

<img src="https://user-images.githubusercontent.com/81943525/196997079-1c3d62c4-7de4-4ad4-b4cf-ced0a3622488.gif" width="250">

## 🧐 참고 사항
- 늦어서 미안합니다.
- 이쁘게 봐주세요

## 📄 Reference

2022-10-21 00:54 UTC, LentoAssai requested changes
# 루미 고생하셨습니다!

애니메이션은 어디갔죠... ㅠㅠ

2022-10-21 00:54 UTC, LentoAssai commented on Sources/Presenter/Feed/FeedCoordinator.swift
> +        navigationController.isNavigationBarHidden = true
nav-bar는 아직 구현안된건가용??

2022-10-21 00:54 UTC, LentoAssai commented on Sources/Presenter/Feed/FeedViewController.swift
> +//  FeedTestViewController.swift
FeedViewController로 파일 변경했으니까 이것도 수정 부탁

2022-10-21 00:54 UTC, LentoAssai commented on Sources/Presenter/Feed/FeedViewController.swift
> +    }
Layout 관련하지 않은 코드들이 있는거같아여

2022-10-21 00:54 UTC, LentoAssai commented on Sources/Presenter/Feed/FeedCell.swift
> +    static let identifier = "FeedCollectionViewCell"
파일명, 클래스 이름, 위에 파일 설명 주석, identifier에 들어가는 이름까지 통일 부탁드려요
그리고 collectionView의 cell이니까 파일 클래스 이름을 FeedCollectionViewCell 과 같이 ~~~CollectionViewCell로 부탁

2022-10-21 00:54 UTC, LentoAssai commented on Sources/Presenter/Feed/FeedViewModel.swift
> +//  FeedTestViewModel.swift
이것도 변경 부탁

2022-10-21 00:54 UTC, LentoAssai commented on Sources/Presenter/Feed/TagCell.swift
> +    static let identifier = "TagCell"
2222
~~CollectionViewCell

2022-10-21 00:54 UTC, LentoAssai commented on Sources/Utility/Extensions/UILabel+.swift
> +    }
extension에 추가하는 메소드는 docc 설명 있으면 좋을거같아요
메소드 클릭하고 `option + command + /` ㄱㄱ

2022-10-21 00:54 UTC, LentoAssai commented on Sources/Presenter/Feed/TagCell.swift
> +    }
static 메소드로 셀 사이즈 잡는거는 처음보네요😳

근데 size 잡는 일을 하는 친구인데 name까지 설정하는게 이상해보여요
메소드 이름을 바꾸던가 name은 다른 곳에서 잡아주면 좋을듯

2022-10-21 00:54 UTC, LentoAssai commented on Sources/Presenter/Feed/TagCell.swift
> +    }
밑에 configure에서 name을 잡아주니까 VC에서 fittingSize를 부르면서 같이 name을 설정해주지말고
fittingSize로는 사이즈만, 그리고 configure를 따로 호출해주는 것도 하나의 방법일 듯 하네여

2022-10-21 00:54 UTC, LentoAssai commented on Sources/Presenter/Feed/FeedCell.swift
> +    private var bottomView = UIView(frame: CGRect(x: 0, y: 0, width: UIScreen.main.bounds.width, height: UIScreen.main.bounds.height * 0.35))
```swift
UIScreem.main.bounds.width
```
요런 사이즈 관련해서는
Util 디렉토리 안에 `DeviceInfo` 파일에 있으니까 이거 사용하면 편하게 사용 가능

2022-10-21 00:54 UTC, LentoAssai commented on Sources/Presenter/Feed/FeedCell.swift
> +    }
> you should only reset attributes of the cell that are not related to content, for example, alpha, editing, and selection state

공식 문서를 보면 reuse 될 때 자동으로 content는 지워줘서 `prepareForReuse`에서는 content와 무관한 것들을 다시 설정할 때 사용하라고 하는 것 같아요
`prepareForReuse` 지우고 실행해봐도 정상작동 할까용??

2022-10-21 00:54 UTC, LentoAssai commented on Sources/Presenter/Feed/FeedCell.swift
> +    private let followButton = UIButton()
셀 안에 들어가는 View들을 grouping해서 하나의 파일로 걷어내거나 Stack으로 묶어주면 조금 더 깔끔해질 것 같아요

2022-10-21 00:54 UTC, LentoAssai commented on Sources/Presenter/Feed/FeedCell.swift
> +    }
`setScrollView`가 init에서도 실행되고, VC에서 cellForRow에서 `cell.configure`를 호출하는데, configure에서도 실행이 되네여

2022-10-21 00:54 UTC, LentoAssai commented on Sources/Presenter/Feed/FeedCell.swift
> +    }
internal ACL은 지워도 될 것 같네여

2022-10-21 00:54 UTC, LentoAssai commented on Sources/Presenter/Feed/FeedCell.swift
> +        followButton.addTarget(self, action: #selector(didTapFollowMapButton), for: .touchUpInside)
addSubViews 라는 메소드에 들어가는 코드는 아닐 거 같아여

2022-10-21 00:54 UTC, LentoAssai commented on Sources/Presenter/Feed/FeedCell.swift
> +        let tapgestureRecognizer = UITapGestureRecognizer(target: self, action: #selector(didTapCourseDetailLabel))
camel이 이상해여

2022-10-21 00:54 UTC, LentoAssai commented on Sources/Presenter/Feed/FeedCell.swift
> +    private var isBodyTapped: Bool = false
`isBodyTapped` 라는 친구가 더보기 상태인지 아닌지를 판별하는 친구인데,
지금 변수명보다는 `isBodyCollapsed` 같이 '탭이 되었다!' 라는 뜻을 가지는 것 보다는 '더보기가 접혀있다, 커져있다' 등의 뜻을 가지는 변수로 바꾸는게 좀 더 좋아보여요

2022-10-21 00:54 UTC, LentoAssai commented on Sources/Presenter/Feed/FeedCell.swift
> +    private var isBodyTapped: Bool = false
isBodyTapped는 '탭이 되었다'는 뜻이니까 누를 때 마다 true값을 가져야  할 것만 같은 변수명으로 다가오네요

2022-10-21 00:54 UTC, LentoAssai commented on Sources/Presenter/Feed/FeedCell.swift
> +            attrString.addAttribute(NSAttributedString.Key.paragraphStyle, value: paragraphStyle, range: NSMakeRange(0, attrString.length))
이거 린트룰 하나 뜨지 않나요...ㅠㅠ 해결법좀

2022-10-21 00:54 UTC, LentoAssai commented on Sources/Presenter/Feed/FeedCell.swift
> +            bottomViewHeight += CGFloat(bodyLabel.countCurrentLines()) * ( bodyLabel.font.lineHeight + 4)
곱하기 뒤에 괄호 뒤에 띄어쓰기 지워주세요

2022-10-21 00:54 UTC, LentoAssai commented on Sources/Presenter/Feed/FeedCell.swift
> +    }
`setCollectionView`니까 지금 열려있는 FeedCollectionView와 관련한건지, 안에 있는 TagCollectionView와 관련한건지 한번에 알기가 어려운 것 같아요

2022-10-21 00:56 UTC, LentoAssai commented on Sources/Presenter/Feed/FeedCoordinator.swift
> +        navigationController.isNavigationBarHidden = true
이 아니라 원래 없네요 ㅋㅋ

2022-10-21 00:59 UTC, LentoAssai commented on Sources/Presenter/Feed/FeedCell.swift
> +        followButton.addTarget(self, action: #selector(didTapFollowMapButton), for: .touchUpInside)
그리구 `UIView` extension으로 `addSubviews()`라는 메소드가 있어서 이름이 비슷하면 좀 헷갈릴 것 같아요

2022-10-21 01:28 UTC, luminouxx commented on Sources/Presenter/Feed/FeedCoordinator.swift
> +        navigationController.isNavigationBarHidden = true
넹 ㅋ

2022-10-21 01:29 UTC, luminouxx commented on Sources/Presenter/Feed/FeedViewController.swift
> +    }
들켰네요

2022-10-21 01:29 UTC, luminouxx commented on Sources/Presenter/Feed/FeedViewController.swift
> +    }
수정하겠습니다.

2022-10-21 01:30 UTC, luminouxx commented on Sources/Presenter/Feed/FeedCell.swift
> +    static let identifier = "FeedCollectionViewCell"
아하 이걸 캐치못했네요

2022-10-21 01:31 UTC, luminouxx commented on Sources/Presenter/Feed/FeedCell.swift
> +    private var bottomView = UIView(frame: CGRect(x: 0, y: 0, width: UIScreen.main.bounds.width, height: UIScreen.main.bounds.height * 0.35))
아하

2022-10-21 01:33 UTC, LentoAssai commented on Sources/Presenter/Feed/FeedViewController.swift
> +    }
<img width="260" alt="스크린샷 2022-10-21 10 33 28" src="https://user-images.githubusercontent.com/88371913/197090512-1ba818e7-c534-434b-b890-22cf6e08f2f6.png">

2022-10-21 07:57 UTC, luminouxx commented on Sources/Presenter/Feed/FeedViewController.swift
> +//  FeedTestViewController.swift
수정했습니다!

2022-10-21 08:01 UTC, luminouxx commented on Sources/Presenter/Feed/FeedCell.swift
> +    static let identifier = "FeedCollectionViewCell"
수정했습니다.

2022-10-21 08:02 UTC, luminouxx commented on Sources/Presenter/Feed/FeedViewModel.swift
> +//  FeedTestViewModel.swift
수정했습니다.

2022-10-21 08:03 UTC, luminouxx commented on Sources/Presenter/Feed/TagCell.swift
> +    static let identifier = "TagCell"
수정했습니다.

2022-10-21 08:06 UTC, luminouxx commented on Sources/Utility/Extensions/UILabel+.swift
> +    }
네 반영했습니다.

2022-10-21 08:15 UTC, luminouxx commented on Sources/Presenter/Feed/TagCell.swift
> +    }
이름을 잡는 기능이 아닌, tagCollectionView의 라벨의 크기를 정해주는 함수 입니다.
cell의 사이즈를 정해야하기 때문에 나중에 넣을, name을 한번 넣고, 그 라벨의 크기에 맞게 적당한 셀의 크기를 리턴하는 함수입니다.
한 가지 기능을 담당하고 있어요. 스태틱으로 선언한 이유도 메모리에 올리지 않은 채로 단지 셀 크기 계산을 하기 위해서구용

2022-10-21 08:18 UTC, luminouxx commented on Sources/Presenter/Feed/FeedCell.swift
> +    private var bottomView = UIView(frame: CGRect(x: 0, y: 0, width: UIScreen.main.bounds.width, height: UIScreen.main.bounds.height * 0.35))
반영했습니다. 감사합니다.

2022-10-21 08:19 UTC, luminouxx commented on Sources/Presenter/Feed/FeedCell.swift
> +    }
몰랐는데 새로하나 배웁니다 감사합니다.

2022-10-21 08:22 UTC, luminouxx commented on Sources/Presenter/Feed/FeedCell.swift
> +    private let followButton = UIButton()
이 부분은 앞으로 수정이 있을 것 같아서 다음번에 반영하겠습니다.

2022-10-21 08:22 UTC, luminouxx commented on Sources/Presenter/Feed/FeedCell.swift
> +    }
네 반영했습니다.

2022-10-21 08:27 UTC, luminouxx commented on Sources/Presenter/Feed/FeedCell.swift
> +        followButton.addTarget(self, action: #selector(didTapFollowMapButton), for: .touchUpInside)
setButton으로 이사했습니다.
AddSubviewToSuperview로 닉변했습니다.

2022-10-21 08:28 UTC, luminouxx commented on Sources/Presenter/Feed/FeedCell.swift
> +        let tapgestureRecognizer = UITapGestureRecognizer(target: self, action: #selector(didTapCourseDetailLabel))
찰린트 쩌네요 반영했습니다.

2022-10-21 08:29 UTC, luminouxx commented on Sources/Presenter/Feed/FeedCell.swift
> +    private var isBodyTapped: Bool = false
isn't body Tapped는 어떨까요

2022-10-21 08:30 UTC, luminouxx commented on Sources/Presenter/Feed/FeedCell.swift
> +    private var isBodyTapped: Bool = false
isBodyCollapsed 로 수정했습니다.

2022-10-21 08:30 UTC, luminouxx commented on Sources/Presenter/Feed/FeedCell.swift
> +            bottomViewHeight += CGFloat(bodyLabel.countCurrentLines()) * ( bodyLabel.font.lineHeight + 4)
이야..... 반영이요

2022-10-21 08:31 UTC, luminouxx commented on Sources/Presenter/Feed/FeedCell.swift
> +    }
setTagCollectionView로 수정

2022-10-21 08:35 UTC, LentoAssai commented on Sources/Presenter/Feed/FeedCell.swift
> +    private var isBodyTapped: Bool = false
isn't she lovely

2022-10-21 08:35 UTC, LentoAssai commented on Sources/Presenter/Feed/FeedCell.swift
> +            attrString.addAttribute(NSAttributedString.Key.paragraphStyle, value: paragraphStyle, range: NSMakeRange(0, attrString.length))
찌찌뽕

2022-10-21 08:41 UTC, LentoAssai approved these changes
어려운 뷰 맡으셔서 잘 구현하셨네요~
고생하셨습니당 👏

2022-10-21 08:41 UTC, LentoAssai commented on Sources/Utility/Extensions/UILabel+.swift
> +    /// UILabel의 texg의 현재 줄 개수를 리턴합니다.
오타요~

2022-10-21 08:41 UTC, LentoAssai commented on Sources/Presenter/Feed/TagCollctionViewCell.swift
> +    static let identifier = "TagCollctionViewCell"
collction 오타요~

2022-10-21 08:44 UTC, luminouxx commented on Sources/Presenter/Feed/TagCollctionViewCell.swift
> +    static let identifier = "TagCollctionViewCell"
죄송함다 ;;

2022-10-22 14:14 UTC, wody-d approved these changes
# FeedCollectionViewCell의 코드가 인상적이었습니다. 수고하셨습니다!

LGTM!

2022-10-23 03:28 UTC, luminouxx reviewed
머지하겠습니다!

2022-10-24 01:29 UTC, merged