Search 탭 🍷
DeveloperAcademy-POSTECH/MacC-Team-Trying-iOS pull request #66
Opened 2022-10-22 09:33 UTC by kyustudyo

## 🔍 개요

Search 탭 UI 🍷
#7 
#57 

코드가 너무 길어질 것 같아 한번 풀리 하고 가는게 나을 거 같아서요 🍷

## 📝 작업사항
- 코스/행성 Segment View
- 코스/헹성 테이블 뷰 셀

## 📸 스크린샷 또는 영상 🍷

| <img src="https://user-images.githubusercontent.com/77485339/197331801-75500fe6-763b-4f02-a253-493210070704.png" width="250"> | <img src="https://user-images.githubusercontent.com/77485339/197331807-24c6d4b1-b184-4d0e-bcdd-25798720bb3f.png" width="250"> |

https://user-images.githubusercontent.com/77485339/197332121-c1e8c769-601d-4d06-9aba-e7937ceec338.mp4

## 🧐 참고 사항 🍷
 **SearchViewModel에 임시 코드가 있어요.. 현재 데이터 타입과는 모양이 다른 임시 데이터 타입인데요. like, follow 버튼 확인하기위해 잠시 두었습니다 나중에 삭제할게요... SearchViewModel 76번째 줄부터 입니다. 그리고 말입니다 search 기능은 풀리 된다음에 추가할게요! 지금은 제목 정도만 치면 나오는 정도입니다. 
SearchViewModel은 수정이 많이 될 것입니다. 지금은 viewmodel 안보셔도 될듯...**

2022-10-22 12:16 UTC, kimscastle commented on Sources/Presenter/Search/Course/CoursePlanetSegmentedControlView.swift
> +class CoursePlanetSegmentedControlView: UIView {
오타네용 contrl -> controll

2022-10-22 12:17 UTC, kimscastle commented on Sources/Presenter/Search/Course/CoursePlanetSegmentedControlView.swift
> +    var segmentChanged: (CoursePlanet) -> Void = { _ in }
var segmentChanged: ((CoursePlanet)->Void)? 로 선언해놓는건 어떤가요

2022-10-22 14:09 UTC, LentoAssai commented on Sources/Presenter/Search/Course/CoursePlanetSegmentedControlView.swift
> +class CoursePlanetSegmentedControlView: UIView {
??

2022-10-22 15:33 UTC, LentoAssai requested changes
# 뀨햄 고생하셨습니다!

라인 수에 압도당해서 시작부터 힘들었네요... ㅠㅠ
줄일 수 있는 라인들은 줄여서 올려주시면 감사하겠습니당.. ㅎㅎ (빈 라인, 큰 뜻이 없으면 addSubviews도 사용?)

2022-10-22 15:33 UTC, LentoAssai commented on Sources/Presenter/Search/SearchViewModel.swift
> +            .removeDuplicates()
debounce랑 removeDuplicates 한 이유가 궁금해요

2022-10-22 15:33 UTC, LentoAssai commented on Sources/Presenter/Search/SearchViewModel.swift
> +            .dropFirst()
얘는 init에서 빈 문자열을 주는거 때문인가요?

2022-10-22 15:33 UTC, LentoAssai commented on Sources/Presenter/Search/SearchViewModel.swift
> +            .store(in: &cancelbag)
아직 공부를 덜해서 정확히는 모르겟지만
얘네들 나중에 네트워크 통신을 하게되면 multicast나 share를 사용할 수 있지 않을까요??

2022-10-22 15:33 UTC, LentoAssai commented on Sources/Presenter/Search/Course/FollowButton.swift
> +    }
FollowButton이랑 LikeButton 이런것들 파일로 뺀 이유가 재사용 가능성이라면
다른사람들이 알기 쉽도록 주석 달아놓으면 좋을것같아요

2022-10-22 15:33 UTC, LentoAssai commented on Sources/Presenter/Search/Course/CourseTableView.swift
> +            }
weak self 써야할까요?

2022-10-22 15:33 UTC, LentoAssai commented on Sources/Presenter/Search/Course/CoursePlanetSegmentedControlView.swift
> +                }
Main thread에서 실행되나요?

2022-10-22 15:33 UTC, LentoAssai commented on Sources/Presenter/Search/Course/CourseTableView.swift
> +            }
이거 데이터가 잘 이해가 안되는데
course관련 데이터랑 행성 데이터랑 merge 하고 그거를 bind해서 가져온 후 보여주면 똑같은 데이터를 화면만 다르게 보여주는게 아닌가요??
예를 들어, '찰리' 라고 검색을 하면 vm에서 string을 '찰리'라고 받아서 course, planet fetch 메소드를 실행해서 각각 publish 프로퍼티에 저장이 됐다가, merge로 `courseOrPlanets`에 저장이 된 후 이거를 가져와서 보여주면
'찰리'관련 course 검색 결과가 3개, planet관련 검색 결과가 2개라고 가정하면 총 5개의 데이터가 있는데, 이 5개가 다 나오는거 아닌가요?

검색 안에 category가 있으니까 팔로우하기 힘드네요 ㅠㅠ

2022-10-22 15:33 UTC, LentoAssai commented on Sources/Presenter/Search/Course/CoursePlanetSegmentedControlView.swift
> +    }
init에서 프로퍼티를 초기화하고 그거를 view에 적용시키는 이유가 있나요??
해당 view를 사용할 때 어차피 init에 color관련해서는 안넘기는거같은데 그냥 바로 color를 사용하는 view들에 적용하면 되지 않나요?

buttonTitles도 정해져있다고 생각이 드는데 init으로 받는 이유가 궁금해요

2022-10-22 15:36 UTC, LentoAssai commented
### viewModel 안봐도 된다는 말을 리뷰 다 끝나고 봐버렸네요 🤪

2022-10-22 16:03 UTC, LentoAssai commented on Sources/Presenter/Search/SearchViewController.swift
> +    private let navigationTextField = CustomTextField(type: .searchCourseAndPlanet)
nav-bar에 텍스트필드 하나라면
UISearchBar 또는 UISearchController도 생각해볼만 할것같아요 (+ ScopeBar)

2022-10-23 06:35 UTC, kimscastle commented on Sources/Presenter/Search/Course/CourseTableViewCell.swift
> +            make.top.equalToSuperview().offset(20)
보통 top left 를 offset, bottom right를 inset으로 쓰지않나? 아닌가?

2022-10-23 06:46 UTC, kyustudyo commented on Sources/Presenter/Search/Course/CoursePlanetSegmentedControlView.swift
> +class CoursePlanetSegmentedControlView: UIView {
？

2022-10-23 06:47 UTC, kyustudyo commented on Sources/Presenter/Search/Course/CoursePlanetSegmentedControlView.swift
> +    var segmentChanged: (CoursePlanet) -> Void = { _ in }
굿입니다~

2022-10-23 06:48 UTC, kyustudyo commented on Sources/Presenter/Home/AddCourse/Components/TextField/CustomTextField.swift
> +    case searchCourseAndPlanet
좋습니다! 그럼 제가 따로 만들어서 일단 사용하고 있을게요!~!

2022-10-23 07:21 UTC, LentoAssai commented on Sources/Presenter/Search/Course/CourseTableViewCell.swift
> +            make.top.equalToSuperview().offset(20)
아 그런가요?? 전 그냥 super랑은 다 inset 쓰는줄 ㅋㅋ

2022-10-23 07:38 UTC, kyustudyo commented on Sources/Presenter/Search/Course/CourseTableView.swift
> +    var cancelbag = Set<AnyCancellable>()
아니요!! 자세를 고쳐 앉으니까 너무 좋아요  ~👍

2022-10-23 07:41 UTC, kyustudyo commented on Sources/Presenter/Search/Course/CourseTableViewCell.swift
> +            make.top.equalToSuperview().offset(20)
그렇군요~!

2022-10-23 07:42 UTC, kyustudyo commented on Sources/Presenter/Search/Course/LikeButton.swift
> +    }
맞습니다..! 좋아요버튼이 좀 작아서 ..

2022-10-23 08:24 UTC, kyustudyo commented on Sources/Presenter/Search/PhotoImage/CourseImageCollectionView.swift
> +        flowLayout.itemSize = CGSize(width: 113, height: 169)
오 중요한 얘기 감사합니다. 반영했습니다! 1

2022-10-23 08:25 UTC, kyustudyo commented on Sources/Presenter/Search/PhotoImage/CourseImageCollectionViewCell.swift
> +        }
you're right!@~@@~!

2022-10-23 08:25 UTC, kyustudyo commented on Sources/Presenter/Search/SearchTestViewModel.swift
> +
그건 좀 
반영~!

2022-10-23 08:26 UTC, kyustudyo commented on Sources/Presenter/Search/SearchViewModel.swift
> +import UIKit
오 지금보니 다시 좋아졌네요~!

2022-10-23 08:28 UTC, kyustudyo commented on Sources/Presenter/Search/SearchViewModel.swift
> +                SearchPlanet(planetImageString: "MyPlanetImage", planetNameString: "규한행성", isFollow: true, hosts: ["이한규", "엠마왔쓴"])
못참겠네요~!

2022-10-23 08:37 UTC, kyustudyo commented on Sources/Presenter/Search/Course/CoursePlanetSegmentedControlView.swift
> +}
찾았다니 다행이군요~!! 외부에서도 사용해서 전역으로 두었는데.. 더 좋게할수있을까요?

index가 필요해서 int였었는데 다른 방법으로 바꿔서 지금은 없앴습니다 감사하니다 ~!

2022-10-23 08:39 UTC, kyustudyo commented on Sources/Presenter/Search/SearchViewModel.swift
> +        }
ViewController에서 사용돼요~!!
```swift

        viewModel?.bind(navigationTextField, to: \.searchString)

```

2022-10-23 08:40 UTC, kyustudyo commented on Sources/Presenter/Search/SearchViewModel.swift
> +    func fetchCourses(_ string: String = "") {
앗! 지워도되는 코드다....! 감사합니다

2022-10-23 08:43 UTC, kyustudyo commented on Sources/Presenter/Search/SearchViewModel.swift
> +            .removeDuplicates()
0.5초안에 같은 text입력하면 두번 리퀘스트 보내지 않는 걸 의도했는데...
리퀘스트 보내도 괜찮은거면 없애도 될거같아요!

2022-10-23 08:44 UTC, kyustudyo commented on Sources/Presenter/Search/SearchViewModel.swift
> +            .dropFirst()
넵! 
아마 나중에는 바뀔수도 잇을거같아요! viewmodel이!

2022-10-24 04:52 UTC, kyustudyo commented on Sources/Presenter/Search/SearchViewModel.swift
> +            .store(in: &cancelbag)
네 그럴것같습니다~!!

2022-10-24 04:53 UTC, kyustudyo commented on Sources/Presenter/Search/Course/FollowButton.swift
> +    }
좋은 말 같습니다~!

2022-10-24 04:59 UTC, kyustudyo commented on Sources/Presenter/Search/Course/CourseTableView.swift
> +            }
좋겠군요!

2022-10-24 05:13 UTC, kyustudyo commented on Sources/Presenter/Search/Course/CoursePlanetSegmentedControlView.swift
> +                }
Main thread 에서 하니
애니메이션이 안먹히네요...!
다른 코드보니 안해도 되는것같습니다...??

2022-10-24 05:19 UTC, kyustudyo commented on Sources/Presenter/Search/Course/CourseTableView.swift
> +            }
아하 현재는 코스를 가르키고 있다면 course API를 호출하고 행성을 가르키고 있다면 planet API를 호출해요..!
API다루게되면 viewModel 수정이 많을 것 같아요...
 
<img width="354" alt="스크린샷 2022-10-24 오후 2 16 47" src="https://user-images.githubusercontent.com/77485339/197453182-a174a1df-3124-4a82-811a-9375ccf957cc.png">

2022-10-24 05:20 UTC, kyustudyo commented on Sources/Presenter/Search/Course/CoursePlanetSegmentedControlView.swift
> +    }
아 혹시 다른 뷰에서 쓰일까해서... 안 받는거로 할까요?~!?

2022-10-24 05:27 UTC, kyustudyo commented on Sources/Presenter/Search/SearchViewController.swift
> +    private let navigationTextField = CustomTextField(type: .searchCourseAndPlanet)
오 좋은 말씀감사합니다!!
이번에 말고 다음에 바꿔봐도 괜찮을까요?!

2022-10-24 06:02 UTC, LentoAssai commented on Sources/Presenter/Search/Course/CoursePlanetSegmentedControlView.swift
> +    }
다른 뷰에서 쓰인다면 좋습니다!

2022-10-24 06:03 UTC, LentoAssai commented on Sources/Presenter/Search/SearchViewController.swift
> +    private let navigationTextField = CustomTextField(type: .searchCourseAndPlanet)
it's up to u

2022-10-24 06:04 UTC, LentoAssai commented on Sources/Presenter/Search/Course/CoursePlanetSegmentedControlView.swift
> +                }
🧐애니메이션이 안먹는다니 이상하네요..

2022-10-24 15:27 UTC, wody-d approved these changes
# 수고하셨습니다!

여윽시 잘하시군요.
LGTM~

2022-10-24 16:39 UTC, Asher3576 reviewed
수고하셨습니다 규~~~

2022-10-24 16:39 UTC, Asher3576 commented on Sources/Presenter/Search/Course/CourseTableViewCell.swift
> +        imageView.contentMode = .scaleAspectFit
셀에 있는 부분 전부
scaleAspectFit -> scaleAspectFill로 변경해야 할거 같아요!
현재 셀 비율은 4:3인데, 16:9의 비율 이미지가 추가 될경우 좌우 여백이 생겨요!

2022-10-25 01:33 UTC, kyustudyo commented on Sources/Presenter/Search/Course/CoursePlanetSegmentedControlView.swift
> +                }
좀 더 공부하고 말해들릴게욘!

2022-10-25 01:34 UTC, kyustudyo commented on Sources/Presenter/Search/Course/CourseTableViewCell.swift
> +        imageView.contentMode = .scaleAspectFit
오오 감사합니다!
셀에 있는 부분 전부 scaleAspectFill로 변경할게요..!!

2022-10-25 01:37 UTC, LentoAssai approved these changes

2022-10-25 01:37 UTC, kimscastle approved these changes
수고하셧습니다~

2022-10-25 01:59 UTC, merged